const cartActionsTypes = {
  LOAD_CART: 'LOAD_CART',
  LOAD_CART_ERROR: 'LOAD_CART_ERROR',
  INCREASE_PRODUCT_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_PRODUCT_QUANTITY: 'DECREASE_QUANTITY',
  DELETE_PRODUCT: 'DELETE_PRODUCT'
};

export default cartActionsTypes;
